### ISSUE TITLE
Brak sensorów

### ISSUE THREAD

**Issue by casper255** [Antoni-Czaplicki/vulcan-for-hassio#18]
Integracja tworzy tylko encję kalendarza. Nie tworzy żadnych innych encji i sensorów.

Błedy w logach

Szczegóły loga (BŁĘDY)
Logger: homeassistant.components.sensor
Source: custom_components/vulcan/fetch_data.py:214
Integration: Sensor (documentation, issues)
First occurred: 8:01:50 (1 occurrences)
Last logged: 8:01:50

Error while setting up vulcan platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/vulcan/sensor.py", line 97, in async_setup_entry
    "exam": await get_next_exam(client),
  File "/config/custom_components/vulcan/fetch_data.py", line 214, in get_next_exam
    async for exam in await client.data.get_exams():
  File "/usr/local/lib/python3.9/site-packages/vulcan/data/_exam.py", line 61, in get
    yield Exam.load(exam)
  File "/usr/local/lib/python3.9/site-packages/vulcan/model/_serializable.py", line 49, in load
    return to_model(cls, data)
  File "/usr/local/lib/python3.9/site-packages/related/functions.py", line 104, in to_model
    value = cls(**value)
TypeError: __init__() missing 1 required positional argument: 'team_class'

**Comment by Antoni-Czaplicki** [comment]
Wiem o tym problemie i pracuję nad jego naprawą. Do tej pory umieściłem już poprawkę w API i na razie czekam na wydanie nowej wersji API z której korzysta integracja.

**Comment by casper255** [comment]
Kiedy można się spodziewać wydania nowej wersji API?

**Comment by Antoni-Czaplicki** [comment]
Niestety nie mogę zapewnić żadnej konkretnej daty, lecz spodziewam się że zostanie to naprawione do końca tygodnia

**Comment by Antoni-Czaplicki** [comment]
Nowa wersja API została już wydana, pracuję aktualnie nad dostosowaniem integracji i jeszcze dzisiaj powinna pojawić się wersja beta

**Comment by casper255** [comment]
W takim razie czekam. Jak będzie to testuję.

**Comment by Antoni-Czaplicki** [comment]
Jest już nowa wersja

**Comment by casper255** [comment]
Wygląda na to że działa poprawnie.

**Comment by casper255** [comment]
Integracja nie pokazuje aktualnych wiadomości. Ostatnią która się pokazuje to ostatnia z teszłego roku szkolnego.
