### ISSUE TITLE
Integracja nie pokazuje aktualnych wiadomości.

### ISSUE THREAD

**Issue by Antoni-Czaplicki** [Antoni-Czaplicki/vulcan-for-hassio#19]
Integracja nie pokazuje aktualnych wiadomości. Ostatnią która się pokazuje to ostatnia z teszłego roku szkolnego.

_Originally posted by @casper255 in https://github.com/Antoni-Czaplicki/vulcan-for-hassio/issues/18#issuecomment-912940019_

**Comment by Antoni-Czaplicki** [comment]
@casper255 czy logi pokazują jakiś błąd?

**Comment by casper255** [comment]
W logach czysto.

**Comment by casper255** [comment]
Od ostatkiej aktualizacji integracji przyszly juz 4 wiadomosci. W encji nadal jest stara wiadomosc

**Comment by Antoni-Czaplicki** [comment]
Sprawdź czy pojawiają się one w aplikacji mobilnej dzienniczek Vulcan

**Comment by casper255** [comment]
W aplikacji sa. O dziwo nawet aplikacja daje powiadomienia

W dniu 4 wrz 2021, 13:04, o 13:04, użytkownik Czapla ***@***.***> napisał:

**Comment by Antoni-Czaplicki** [comment]
A czy inne sensory działają poprawnie?
Oraz jaki jest interwał aktualizacji

**Comment by casper255** [comment]
Wyglada ze tak. Co prawda lekcje na jutro pokazuja sie juz z poniedzialku. Obecnosci pokazywalo ok, ocen jeszcze nie ma. Interwal aktualizacji 2h

W dniu 4 wrz 2021, 13:08, o 13:08, użytkownik Czapla ***@***.***> napisał:

**Comment by Antoni-Czaplicki** [comment]
Możesz jeszcze spróbować przeładować integrację

**Comment by casper255** [comment]
To juz robilem. Nic sie nie zmienilo. Probowalem tez przeinstalowac. To tez nic nie zmienilo

W dniu 4 wrz 2021, 13:21, o 13:21, użytkownik Czapla ***@***.***> napisał:

**Comment by casper255** [comment]
Dziwne jest to te w ustawieniach aplikacji jest interwal 5min a jazda encja aktualizuje sie po 2h

W dniu 4 wrz 2021, 13:21, o 13:21, użytkownik Czapla ***@***.***> napisał:

**Comment by casper255** [comment]
Po restarcie w logach pojawia się ostrzeżenie

Logger: homeassistant.components.sensor
Source: /usr/local/lib/python3.9/asyncio/events.py:80
Integration: Sensor (documentation, issues)
First occurred: 17:30:04 (1 occurrences)
Last logged: 17:30:04

Setup of sensor platform vulcan is taking over 10 seconds.

**Comment by casper255** [comment]
Dziś lekcje na dziś i jutro nie pokrywają się z planem. W kalendarzu są ok ale na dziś pokazuje jutrzejsze a na jutro wogóle nie ma takiego zestawienia w planie
![Screenshot_20210905-074313_Home Assistant](https://user-images.githubusercontent.com/63518124/132116767-a0c2de66-b346-4fc4-a4d5-fcf991a87c31.jpg)
![Screenshot_20210905-073730_Home Assistant](https://user-images.githubusercontent.com/63518124/132116772-5ae8e6ae-c26b-4578-9e51-f709486af549.jpg)

W logach błędów brak.

**Comment by Antoni-Czaplicki** [comment]
Jak się okazało, problem z pomieszanymi lekcjami w sensorach leżał po stronie Vulcana (aktualizacja pobierania planu lekcji poprzez API) i czekam aktualnie na wydanie kolejnej wersji

**Comment by Antoni-Czaplicki** [comment]
Problem z pomieszanymi lekcjami został już naprawiony w nowej wersji 🎉

**Comment by casper255** [comment]
Zaktualizowane, testuję. Plan i lekcje pokazuje na ten moment właściwie. Zobaczę jak będzie na przestrzeni dni. Wiadomości nadal pokazuje stare. Zobaczę jak przyjdzie jakaś nowa. 

W dniu 7 wrz 2021, 06:41, o 06:41, użytkownik Czapla ***@***.***> napisał:

**Comment by Antoni-Czaplicki** [comment]
Niestety nie mam pojęcia co może powodować problem z nie aktualizująca się wiadomością, u mnie wszystko działa

**Comment by casper255** [comment]
Czekam aż będzie ze szkoły nowa wiadomość i wtedy się wyjaśni

W dniu 8 wrz 2021, 11:29, o 11:29, użytkownik Czapla ***@***.***> napisał:

**Comment by casper255** [comment]
W skrzynce w dzienniku było chyba zbyt dużo starych wiadomości. Po usunięciu zaczęło działać poprawnie. Można zamknąć
