### ISSUE TITLE
Sprawdziany - pokazują tylko 1 rekord w całym tygodniu

### ISSUE THREAD

**Issue by mario5046** [Antoni-Czaplicki/vulcan-for-hassio#21]
Czy istnieje możliwość, aby encje Exam pokazywały wszystkie sprawdziany zaplanowane w danym tygodniu kalendarzowym ? W chwili obecnej pokazują tylko 1 pozycję.

**Comment by Antoni-Czaplicki** [comment]
Niestety nie ma możliwości zmieszczenia kilku sprawdzianów w jednej encji, a nie chciał bym robić kilka dodatkowych encji które i tak często nie będą używane. Mam w planach dodanie do kalendarza sprawdzianów i zadań domowych, ale nie mam pojęcia kiedy będę miał czas się tym zająć
