### ISSUE TITLE
[Home Assistant 2022.4.6] Po skonfigurowaniu widać tylko encję kalendarz

### ISSUE THREAD

**Issue by majkers** [Antoni-Czaplicki/vulcan-for-hassio#28]
Witam,
używam Home Assistant 2022.4.6 i właśnie skonfigurowałem tę integrację. Nie wiem czy to dlatego, że jest niedziela, ale nie widzę żadnych błędów w logu a jedyna encja, któa mi się utworzyła to kalendarz. Czy to znany problem?

**Comment by majkers** [comment]
Tyle mam w logach:

```
2022-04-24 12:32:27 INFO (MainThread) [client] Getting Vulcan components...
2022-04-24 12:32:27 INFO (MainThread) [client] Registering to lublin...
2022-04-24 12:32:28 INFO (MainThread) [client] Successfully registered as XXX@op.pl
```

**Comment by Antoni-Czaplicki** [comment]
Rozumiem że używasz domyślnej integracji?

**Comment by majkers** [comment]
Zgadza się.

**Comment by Antoni-Czaplicki** [comment]
W integracji domyślnej na razie jest dostępny tylko kalendarz, aby uzyskać resztę encji trzeba zainstalować niestandardową integrację.

**Comment by majkers** [comment]
Dzięki i przepraszam, nie doczytałem...
