### ISSUE TITLE
Brak encji kalendarza

### ISSUE THREAD

**Issue by casper255** [Antoni-Czaplicki/vulcan-for-hassio#30]
Po ostatniej aktualizacji zniknęły encje kalendarza

**Comment by Antoni-Czaplicki** [comment]
U mnie wszystko działa, jest coś w logach?

**Comment by casper255** [comment]
Logger: homeassistant.setup
Source: setup.py:298
First occurred: 17:17:45 (1 occurrences)
Last logged: 17:17:45

Unable to prepare setup for platform vulcan.calendar: Platform not found (cannot import name 'CalendarEntity' from 'homeassistant.components.calendar' (/usr/src/homeassistant/homeassistant/components/calendar/__init__.py)).

**Comment by casper255** [comment]
![Uploading Screenshot_20220505-174134_Home Assistant.jpg…]()

**Comment by casper255** [comment]
2022.4.7
Vulcan z hacs 0.13.0

**Comment by casper255** [comment]
Do 2022.5 jest zbyt duzo insue do rzeczy z ktorych korzystam wiec nie jestem w stanie na ten moment na niego przejsc

**Comment by Antoni-Czaplicki** [comment]
W takim razie jedyne co ci pozostało to powrócić do 12.2
