### ISSUE TITLE
Po aktualizacji do wersji 0.13 błąd w logach i nie ma encji kalendarza

### ISSUE THREAD

**Issue by majkers** [Antoni-Czaplicki/vulcan-for-hassio#32]
Witam,

po aktualizacji do nowej wersji mam coś takiego w logach:

`Unable to prepare setup for platform vulcan.calendar: Platform not found (cannot import name 'CalendarEntity' from 'homeassistant.components.calendar' (/usr/src/homeassistant/homeassistant/components/calendar/__init__.py)).`

i nie tworzy się encja kalendarza.

**Comment by Antoni-Czaplicki** [comment]
Zobacz #30
