### ISSUE TITLE
Nie pobiera wiadomości z nowego "Wiadomości Plus"

### ISSUE THREAD

**Issue by Mr-Groch** [Antoni-Czaplicki/vulcan-for-hassio#33]
W tym roku wprowadzone zostało nowe "Wiadomości Plus". Integracja nie pobiera z nich wiadomości - wyświetla ciągle ostatnią wiadomość ze starych "Wiadomości" z zeszłego roku szkolnego.

Wraz z wprowadzeniem nowych "Wiadomości Plus" dostałem taką oto wiadomość, może będzie pomocna:

> Drodzy uczniowie i rodzice!
> 
> Nowy rok szkolny rozpoczynamy w e-dzienniku z nowym modułem Wiadomości. Znajdziecie go na Witrynie rodzica i ucznia oraz w aplikacji mobilnej Dzienniczek VULCAN. Nie trzeba nic robić, nowy moduł już na Was czeka.
> 
> Nowy rok to nowe otwarcie, więc skrzynka odbiorcza będzie pusta, a stare wiadomości znajdziecie w archiwum.
> 
> Więcej informacji o wiadomościach w aplikacji mobilnej znajdziecie tutaj: https://www.vulcan.edu.pl/strona/nowy-modul-wiadomosci-934
> 
> 
> 
> Życzymy Wam wielu sukcesów w nowym roku szkolnym!
> 
> Pozdrawiamy
> 
> Zespół VULCAN
>

**Comment by greengo1** [comment]
Potwierdzam, wszystko poza tym działa świetnie. Dzięki za poświęcony czas!

**Comment by Antoni-Czaplicki** [comment]
Rzeczywiście, najwyraźniej nastąpiła jakaś zmiana w API Hebe której się nie spodziewaliśmy. Wraz z [szkolny.eu](https://szkolny.eu/) szukamy teraz możliwej przyczyny tego błędu oraz jak tylko uda nam się go naprawić integracja zostanie zaktualizowana

**Comment by Antoni-Czaplicki** [comment]
Zaimplementowano w najnowszej wersji
https://github.com/Antoni-Czaplicki/vulcan-for-hassio/releases/latest
