### ISSUE TITLE
1 urządzenie 1 encja

### ISSUE THREAD

**Issue by kurako92** [Antoni-Czaplicki/vulcan-for-hassio#34]
Witam,

Po uruchomieniu integracji jest znajdowana tylko jedna encja - calendar.
Plan lekcji widnieje w kalendarzu, nie pojawiają się żadne informacje odnośnie zadań domowych ani wiadomosci od nauczyciela.
**
![image](https://user-images.githubusercontent.com/63018395/188935111-8ceec78d-0f13-489c-93cd-1ac08f491f74.png)
**

**Comment by Antoni-Czaplicki** [comment]
Zobacz #28

**Comment by Antoni-Czaplicki** [comment]
Naprawione w ostatniej wersji
https://github.com/Antoni-Czaplicki/vulcan-for-hassio/releases/latest
