### ISSUE TITLE
Offset kalendarz

### ISSUE THREAD

**Issue by adek1990** [Antoni-Czaplicki/vulcan-for-hassio#37]
Cześć,

czy mógłbym prosić o dodanie np. 30min offsetu w calendarzu przed pierwszymi zajęciami lub przed każdymi. Offset jak i przed którą lekcją w dany dzień możnabyłoby ustawiać w configu integracji.  Bardzo ułatwiłoby mi to automatyzację jak :D

**Comment by Antoni-Czaplicki** [comment]
Dodawanie offsetu w taki sposób zepsułoby wygląd kalendarza i jego funkcjonowanie i nie planuję tego implementować, jeśli chcesz to możesz zmodyfikować integrację lokalnie, albo jeszcze lepiej - dostosować swoją automatyzacje
