### ISSUE TITLE
[FR] multiple students 

### ISSUE THREAD

**Issue by ciechompl** [Antoni-Czaplicki/vulcan-for-hassio#4]
Please consider adding multiple students config. 
I see 2 ways: 
- easy: allow component to be added multiple times into the integration config and just add/adjust some prefixes to the sensors to easy recognize which coms from which student/integration 
- complex: allow in the component itself to select more than 1 student as currently in the options there is only possibility to choose 1 student.

**Comment by Antoni-Czaplicki** [comment]
Please try newest version: https://github.com/Antoni-Czaplicki/vulcan-for-hassio/releases/tag/v0.8
