### ISSUE TITLE
async_setup_platforms

### ISSUE THREAD

**Issue by mariuszxeno** [Antoni-Czaplicki/vulcan-for-hassio#41]
Logger: homeassistant.helpers.frame
Source: helpers/frame.py:77
First occurred: 07:39:43 (1 occurrences)
Last logged: 07:39:43

Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. Please report issue to the custom integration author for vulcan using this method at custom_components/vulcan/__init__.py, line 43: hass.config_entries.async_setup_platforms(entry, PLATFORMS)

Uonet+ Vulcan integration for Home Assistant
version 0.14.2

**Comment by Antoni-Czaplicki** [comment]
Please try updating integration to the master branch
