### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by korzeniewski36** [Antoni-Czaplicki/vulcan-for-hassio#47]
When it comes to me?? My entire HA was clogged up, undecided errors
![Przechwytywanie](https://github.com/Antoni-Czaplicki/vulcan-for-hassio/assets/38017270/8c457a99-fcf7-40f7-8b92-b41b53e1e54e)

**Comment by korzeniewski36** [comment]
Yes, I registered a new device. The problem is not gone, restarting the system does not help. The only thing is that the add-on started working properly. HA I'm still confused

**Comment by Antoni-Czaplicki** [comment]
Hi, please check if the issue still exists
