### ISSUE TITLE
Nie można dodać dzienniczka

### ISSUE THREAD

**Issue by Wielebny666** [Antoni-Czaplicki/vulcan-for-hassio#48]
Ten błąd pochodzi z niestandardowej integracji.

Logger: custom_components.vulcan.config_flow
Source: custom_components/vulcan/config_flow.py:87
Integration: Uonet+ Vulcan (documentation, issues)
First occurred: 18:42:18 (1 occurrences)
Last logged: 18:42:18

Connection error: Cannot connect to host uonetplus-komunikacja.edu.gdansk.pl:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')]

**Comment by Antoni-Czaplicki** [comment]
Możesz sprawdzić czy problem nadal występuje?

**Comment by Wielebny666** [comment]
już nie
