### ISSUE TITLE
Problem z sensor.latest_message po dodaniu drugiego ucznia.

### ISSUE THREAD

**Issue by lukdwo** [Antoni-Czaplicki/vulcan-for-hassio#51]
Po dodaniu drugiego ucznia pobierany atrybut sensor.latest_message jest pobierany z wiadomości pierwszego ucznia tzn. ostatnia wiadomość dla dwóch uczniów jest taka sama.
HA: 2024.1.5
Uonet+ Vulcan: 0.15.1

**Comment by Antoni-Czaplicki** [comment]
We are waiting for new vulcan-api release: https://github.com/kapi2289/vulcan-api/pull/139
