### ISSUE TITLE
Znaczniki nowych linii w latest_message content

### ISSUE THREAD

**Issue by kaaac** [Antoni-Czaplicki/vulcan-for-hassio#57]
Witam.

W podglądzie wiadomości z aplikacji wyświetlają się "odstępy" po każdym akapicie. Natomiast w integracji atrybut Content encji latest_message nie zawiera w tych miejscach nawet znacznika nowej linii - zarówno w podglądzie atrybutu jak i na karcie markdown.

Pozdrawiam!

**Comment by Antoni-Czaplicki** [comment]
Hej, możesz wysłać ss?

**Comment by kaaac** [comment]
Jasne!
![image](https://github.com/Antoni-Czaplicki/vulcan-for-hassio/assets/74159167/f157921b-c9c0-463c-b854-3e0b9899e8ab)
![image](https://github.com/Antoni-Czaplicki/vulcan-for-hassio/assets/74159167/452169df-fe04-4e06-a5f6-43b3311459c5)
![image](https://github.com/Antoni-Czaplicki/vulcan-for-hassio/assets/74159167/63f8ce02-0621-4378-bd3a-4d75ceda95d7)

**Comment by kaaac** [comment]
Jeśli byłyby znaczniki w atrybucie, mozna by było sobie wyświetlić w karcie wewnątrz znacznika ``` ````. W ten sposób formatowanie powinno być poprawne na frontend, przynajmniej znaki nowych linii. przykład:

![image](https://github.com/Antoni-Czaplicki/vulcan-for-hassio/assets/74159167/1b7cfb0d-a7ad-4289-b873-1e1bc8cd74da)

![image](https://github.com/Antoni-Czaplicki/vulcan-for-hassio/assets/74159167/d4422c22-5300-40e4-a14d-e2a8621bfd68)

**Comment by Antoni-Czaplicki** [comment]
Aaa, ok - patrzyłem tylko na to jak się wyświetlały w szczegółach encji. Za kilka minut wrzucę nową wersję

**Comment by Antoni-Czaplicki** [comment]
https://github.com/Antoni-Czaplicki/vulcan-for-hassio/releases/tag/0.16.1

**Comment by kaaac** [comment]
Dziękuję!
